from symtable import Class


class ErrorPartitura:
    ...
class ContieneNumero:
    ...
class ContieneCaracterInvalido:
    ...
class SinNotas:
    ...
class EspacioMultiple:
    ...
class EspacioBordes:
    ...
class ErrorArchivo:
    ...
class ArchivoNoEncontrado:
    ...
class ArchivoCorrupto:
    ...